version: "3"

services:
  reseedar:
    environment:
      - NODE_ENV="development"
    build: .
    volumes:
      - .:/usr/src/app
      - ./config:/config
    ports:
      - 3434:3434
      - 9229:9229
    command: npm start
